# Generated by Django 4.1.3 on 2022-11-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_customer_phone'),
        ('contract', '0003_alter_contract_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer'),
        ),
    ]
