# Generated by Django 4.1.3 on 2022-11-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('mothermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.mothermodel')),
                ('active_customer', models.BooleanField()),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=12)),
                ('customer_adress', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contact', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.mothermodel',),
        ),
    ]
