# Generated by Django 4.1.3 on 2022-11-24 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
        ('customer', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_customer', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=12),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='event_sales_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_sales_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('FUTURE', 'Future'), ('ONGOING', 'Ongoing'), ('ENDED', 'Ended')], default='FUTURE', max_length=30, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_support_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_support_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='event',
            name='related_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
    ]
