# Generated by Django 4.1.3 on 2022-11-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
        ('event', '0002_event_attendees_event_event_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_sales_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sales_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_support_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_support_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='event',
            name='related_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
    ]
